# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  - name: Publications
    url: /#Publications
    weight: 11
  - name: Research
    url: research/
    weight: 20
  - name: Software
    url: software/
    weight: 30
  - name: CV
    url: cv/
    weight: 40
